### ISSUE TITLE
Question about lucia adapters

### ISSUE THREAD

**Issue by MonsignorEduardo** [Octo8080X/fresh_lucia_plugin#1]
Hey, firsty thanks for the project quite easy to use and cleans quite a bit of code.
I was wondering what lucia adapter do you recomend.

**Comment by Octo8080X** [comment]
@MonsignorEduardo 

Thank you very much.
I am very happy.

We have confirmed that it works on both [mysql](https://lucia-auth.com/database-adapters/mysql2/) [redis](https://lucia-auth.com/database-adapters/redis/). (I am sorry that I have not been able to confirm that it works with all adapters).

I am aware that all of the adapters can be used because of the abstraction.

If you want to run it with deno deploy, [Upstash Redis](https://lucia-auth.com/database-adapters/upstash-redis/) would be relatively inexpensive.

There is a 3rd party who makes adapters with Deno KV, which may also be helpful.
https://github.com/JLarky/astro-lucia-deno-kv

**Comment by MonsignorEduardo** [comment]
Thanks, will check ^_^
